language: node_js
node_js:
  - lts/*
install:
  - npm install # npm ci
script:
  - npm docs:build # npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: 9eafca5f46f22e5cadc3a4cad54ea1d0c964c382
  keep_history: true
  on:
    branch: master
